In [23]:
import pandas as pd

# Load
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
# Alternatively: df = pd.read_csv('titanic.csv')

print("Shape:", df.shape)
print("\n--- First look ---")
df.head()

Shape: (891, 12)

--- First look ---

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
# 1. Shape — how many rows/columns?
print("Shape:", df.shape)

# 2. Column names and types
print(df.dtypes)

# 3. Missing value count per column
print(df.isnull().sum())
print("\nMissing %:")
print(df.isnull().mean().round(3) * 100)

# 4. Duplicates
print("\nDuplicate rows:", df.duplicated().sum())

# 5. Value distribution for key columns
print(df['Sex'].value_counts())
print(df['Pclass'].value_counts())
print(df['Age'].describe())

Shape: (891, 12)
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Missing %:
PassengerId     0.0
Survived        0.0
Pclass          0.0
Name            0.0
Sex             0.0
Age            19.9
SibSp           0.0
Parch           0.0
Ticket          0.0
Fare            0.0
Cabin          77.1
Embarked        0.2
dtype: float64

Duplicate rows: 0
Sex
male      577
female    314
Name: count, dtype: int64
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [3]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [20]:
df['Embarked'].mode()[0]

'S'

In [17]:
# df.loc[int(891/2)-2,'Age']  # Accessing the middle row's 'Age' value
df['Age'].median()  # Median age

28.0

In [25]:
# --- Before: check nulls ---
print(df.isnull().sum())

# Strategy 1: Drop entire column (Cabin - 77% missing, not worth keeping)
df = df.drop(columns=['Cabin'])
print("After dropping Cabin:", df.isnull().sum())

# Strategy 2: Fill with mode (Embarked - only 2 missing)
mode_embarked = df['Embarked'].mode()[0]
print("Most common port:", mode_embarked)
df['Embarked'] = df['Embarked'].fillna(mode_embarked)

# Strategy 3: Impute with median (Age - 20% missing, numeric, important)
median_age=df['Age'].median()
print("Median age:", median_age)
df['Age']=df['Age'].fillna(median_age)

# Validate
print("\nAfter cleaning nulls:")
print(df.isnull().sum())

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

KeyError: "['Cabin'] not found in axis"

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [51]:
import pandas as pd

pd.Series(
    [],
    index=[],
    name=""

)

dup_df = pd.DataFrame([
    # Exact duplicates
    (1, "Apple", 100, "2024-01-01"),
    (1, "Apple", 100, "2024-01-01"),

    # Key duplicate (same order_id, different timestamp)
    (2, "Banana", 50, "2024-01-01 10:00"),
    (2, "Banana", 50, "2024-01-01 10:05"),

    # Near duplicate (same name, different case/spelling)
    (3, "orange", 30, "2024-01-02"),
    (4, "Orange", 30, "2024-01-02"),
], columns=["order_id", "item", "price", "timestamp"])

dup_df

   order_id    item  price         timestamp
0         1   Apple    100        2024-01-01
1         1   Apple    100        2024-01-01
2         2  Banana     50  2024-01-01 10:00
3         2  Banana     50  2024-01-01 10:05
4         3  orange     30        2024-01-02
5         4  Orange     30        2024-01-02

In [12]:
dup_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   order_id   6 non-null      int64
 1   item       6 non-null      object
 2   price      6 non-null      int64
 3   timestamp  6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [52]:
dup_df.drop_duplicates()

   order_id    item  price         timestamp
0         1   Apple    100        2024-01-01
2         2  Banana     50  2024-01-01 10:00
3         2  Banana     50  2024-01-01 10:05
4         3  orange     30        2024-01-02
5         4  Orange     30        2024-01-02

In [58]:
dup_df.sort_values("timestamp").drop_duplicates(subset=["order_id"], keep=False)

   order_id    item  price   timestamp
4         3  orange     30  2024-01-02
5         4  Orange     30  2024-01-02

In [59]:
dup_df["item_clean"] = dup_df["item"].str.lower().str.strip()
dup_df

   order_id    item  price         timestamp item_clean
0         1   Apple    100        2024-01-01      apple
1         1   Apple    100        2024-01-01      apple
2         2  Banana     50  2024-01-01 10:00     banana
3         2  Banana     50  2024-01-01 10:05     banana
4         3  orange     30        2024-01-02     orange
5         4  Orange     30        2024-01-02     orange

In [68]:
dup_df.drop_duplicates(subset=["item_clean"],ignore_index=True)

   order_id    item  price         timestamp item_clean
0         1   Apple    100        2024-01-01      apple
1         2  Banana     50  2024-01-01 10:00     banana
2         3  orange     30        2024-01-02     orange

## **Fixing Data Types**

In [ ]:
import pandas as pd

# --------------------------------------------------
# 1. THE PROBLEM: Storing dates and numbers as strings
# --------------------------------------------------
print("--- THE PROBLEM (Strings) ---")

# Notice that February doesn't have a leading zero, and prices are quoted strings
bad_data = {
    'date': ["2025-11-01", "2025-2-01", "2025-12-01"],
    'price': ["10.50", "5.00", "abc"]
}
df_bad = pd.DataFrame(bad_data)
print("Original Data types:\n", df_bad.dtypes)

# Chronological sorting FAILS because it sorts alphabetically
# "2025-11-01" will incorrectly come BEFORE "2025-2-01"
df_sorted_bad = df_bad.sort_values(by='date')
print("\nIncorrectly Sorted (Alphabetical):")
print(df_sorted_bad)


average = df_bad['price'].mean()

--- THE PROBLEM (Strings) ---
Original Data types:
 date     object
price    object
dtype: object

Incorrectly Sorted (Alphabetical):
         date  price
0  2025-11-01  10.50
2  2025-12-01    abc
1   2025-2-01   5.00

TypeError: Could not convert string '10.505.00abc' to numeric

In [73]:
# --------------------------------------------------
# 2. THE SOLUTION: Converting to proper data types
# --------------------------------------------------
print("--- THE SOLUTION (Proper Types) ---")

df_good = df_bad.copy()

# Convert 'date' string to an actual datetime object
df_good['date'] = pd.to_datetime(df_good['date'])

# Convert 'price' string to a float
df_good['price'] = pd.to_numeric(df_good['price'], errors = "coerce")

print("Fixed Data types:\n", df_good.dtypes)

# Chronological sorting WORKS perfectly now
df_sorted_good = df_good.sort_values(by='date')
print("\nCorrectly Sorted (Chronological):")
print(df_sorted_good)

# Numeric operations WORK perfectly now
average_price = df_good['price'].mean()
print(f"\n✅ Success! The average price is: ${average_price:.2f}")
print(df_good)

--- THE SOLUTION (Proper Types) ---
Fixed Data types:
 date     datetime64[ns]
price           float64
dtype: object

Correctly Sorted (Chronological):
        date  price
1 2025-02-01    5.0
0 2025-11-01   10.5
2 2025-12-01    NaN

✅ Success! The average price is: $7.75
        date  price
0 2025-11-01   10.5
1 2025-02-01    5.0
2 2025-12-01    NaN

In [74]:
import pandas as pd

# 1. Create a highly realistic, messy user-input dataset
df = pd.DataFrame({
    'user_id': ['USR_01', 'USR_02', 'USR_03', 'USR_04', 'USR_05', 'USR_06'],
    # Notice the leading spaces, random capitalizations, and bad typos
    'gender_raw': ['male', '  m  ', 'female', 'f', 'maale', 'FEMALE']
})

print("📋 1. RAW MESSY INPUTS:")
print(df)
print("\n" + "="*50 + "\n")

📋 1. RAW MESSY INPUTS:
  user_id gender_raw
0  USR_01       male
1  USR_02        m
2  USR_03     female
3  USR_04          f
4  USR_05      maale
5  USR_06     FEMALE

==================================================

In [28]:
# 2. STEP ONE: Normalize the text first (Strip spaces and make lowercase)
# This instantly squashes "  m  " to "m" and "FEMALE" to "female"
df['gender_normalized'] = df['gender_raw'].astype(str).str.strip().str.lower()

print("🧹 2. AFTER COARSE CLEANING (.str.strip().str.lower()):")
print(df)
print("\n" + "="*50 + "\n")

🧹 2. AFTER COARSE CLEANING (.str.strip().str.lower()):
  user_id gender_raw gender_normalized
0  USR_01       male              male
1  USR_02        m                   m
2  USR_03     female            female
3  USR_04          f                 f
4  USR_05      maale             maale
5  USR_06     FEMALE            female

==================================================

In [29]:
# 3. STEP TWO: Define a clean, uniform translation dictionary
# Since everything is now lowercase and stripped, our dictionary can be tiny!
clean_map = {
    'male': 'Male',
    'm': 'Male',
    'female': 'Female',
    'f': 'Female'
}


# 4. STEP THREE: Apply .replace()
# 'maale' is not in our dictionary keys, so .replace() leaves it as 'maale' safely.
df['gender_final'] = df['gender_normalized'].replace(clean_map)

print("✅ 3. FINAL OUTPUT MATRIX USING .replace():")
print(df[['user_id', 'gender_raw', 'gender_final']])

✅ 3. FINAL OUTPUT MATRIX USING .replace():
  user_id gender_raw gender_final
0  USR_01       male         Male
1  USR_02        m           Male
2  USR_03     female       Female
3  USR_04          f       Female
4  USR_05      maale        maale
5  USR_06     FEMALE       Female

In [30]:
df['gender_final'] = df['gender_final'].replace('maale', 'Male')

In [32]:
df['gender_normalized'].value_counts()

gender_normalized
female    2
male      1
m         1
f         1
maale     1
Name: count, dtype: int64

In [31]:
df

  user_id gender_raw gender_normalized gender_final
0  USR_01       male              male         Male
1  USR_02        m                   m         Male
2  USR_03     female            female       Female
3  USR_04          f                 f       Female
4  USR_05      maale             maale         Male
5  USR_06     FEMALE            female       Female

# 🎯 Module: Query Thinking vs. Pandas Execution
## Case Study: Analyzing Food Delivery Performance

We have been given a core business question from our operations team:
> **"Which city had the highest average order value last month, among orders that were not cancelled?"**

To solve this, we must break this human English request down into logical data steps.

### The 3-Step Analytical Pipeline:
1. **Filter:** Kick out any orders that were cancelled (and focus on last month's timeframe).
2. **Aggregate:** Group the remaining orders by `city` and calculate the average (`AVG` / `mean`) order cost.
3. **Sort & Extract:** Sort the list from highest average cost to lowest, and take the top result.

In [75]:
import pandas as pd

# Load the Superstore-style dataset
data = {
    'order_id': ['O1','O2','O3','O4','O5','O6','O7','O8'],
    'city': ['Mumbai','Delhi','Mumbai','Bangalore','Delhi','Mumbai','Delhi','Bangalore'],
    'category': ['Tech','Furniture','Tech','Office','Tech','Furniture','Office','Tech'],
    'sales': [25000, 8000, 15000, 3000, 32000, 12000, 5500, 18000],
    'profit': [5000, -500, 3200, 800, 8000, 1200, 600, 4000],
    'status': ['completed','completed','completed','cancelled','completed','completed','cancelled','completed']
}
df = pd.DataFrame(data)
print(df)

  order_id       city   category  sales  profit     status
0       O1     Mumbai       Tech  25000    5000  completed
1       O2      Delhi  Furniture   8000    -500  completed
2       O3     Mumbai       Tech  15000    3200  completed
3       O4  Bangalore     Office   3000     800  cancelled
4       O5      Delhi       Tech  32000    8000  completed
5       O6     Mumbai  Furniture  12000    1200  completed
6       O7      Delhi     Office   5500     600  cancelled
7       O8  Bangalore       Tech  18000    4000  completed

In [34]:
df[['order_id', 'status', 'profit']]

  order_id     status  profit
0       O1  completed    5000
1       O2  completed    -500
2       O3  completed    3200
3       O4  cancelled     800
4       O5  completed    8000
5       O6  completed    1200
6       O7  cancelled     600
7       O8  completed    4000

In [37]:
df[df['sales'] > 10000][['order_id', 'sales']]

# select order_id, sales from data where sales > 10000

  order_id  sales
0       O1  25000
2       O3  15000
4       O5  32000
5       O6  12000
7       O8  18000

# Q1: Show all completed orders from Mumbai

In [38]:
# Pandas
result = df[(df['status'] == 'completed') & (df['city'] == 'Mumbai')]
print(result[['order_id','city','sales','profit']])

  order_id    city  sales  profit
0       O1  Mumbai  25000    5000
2       O3  Mumbai  15000    3200
5       O6  Mumbai  12000    1200

-- SQL equivalent

```
SELECT order_id, city, sales, profit
FROM orders
WHERE status = 'completed'
  AND city = 'Mumbai';

 # Q2. Top 3 orders by sales

In [40]:
# Pandas
top3 = df.sort_values('sales', ascending=False).head(3)
print(top3[['order_id','city','sales']])

  order_id       city  sales
4       O5      Delhi  32000
0       O1     Mumbai  25000
7       O8  Bangalore  18000