### **What is NumPy?**

- NumPy (short for Numerical Python) is the foundational open-source library for scientific computing and data analysis in Python.

- At its core, NumPy provides a powerful, N-dimensional array object called an ndarray.

- While standard Python lists can hold various data types, a NumPy array is tightly packed and designed specifically to hold numbers of the exact same type.

**Why is it Required & What are the Benefits?**

If Python already has lists, why do we need NumPy? There are three massive advantages:

- **Vectorized Operations (No More Loops):** With standard Python lists, if you want to perform math on every single item, you have to write a for loop. NumPy supports vectorization, allowing you to apply a mathematical operation to the entire array in a single line of code.

- **Blazing Fast Performance:** NumPy arrays are written in C under the hood. They store data in contiguous memory blocks, meaning the computer can access the numbers instantly. On large datasets, NumPy can be 100x faster than native Python lists.

- **Multidimensional Architecture:** NumPy effortlessly handles multi-dimensional data like grids, matrices (2D arrays), and cubes (3D arrays) with features like .shape and .reshape() to track rows and columns cleanly.

In [1]:
import numpy as np

# Suppose we want to add 10 to a collection of exam scores
scores_list = [85, 92, 78, 95, 88]
scores_array = np.array(scores_list)
print("numpy array: ", scores_array)

print("list type: ", type(scores_list))
print("numpy array: ", type(scores_array))

# The Standard Python List Way (Requires a loop)
result_list = []
for s in scores_list: 
  result_list.append(s+10)
print("Python List + 10: ", result_list)

# The NumPy Way (Vectorized operation - clean and explicit)
array_result = scores_array + 10
print("NumPy Array + 10....: ", array_result)

numpy array:  [85 92 78 95 88]
list type:  <class 'list'>
numpy array:  <class 'numpy.ndarray'>
Python List + 10:  [95, 102, 88, 105, 98]
NumPy Array + 10....:  [ 95 102  88 105  98]

In [2]:
import time
import numpy as np

# Create a collection of 1 million integers
size = 1_000_000
python_list = list(range(size))
numpy_array = np.arange(size) # (10), (0,1,2,3,4,5,6,7,8,9)

# 1. Time the Python List operation
start_time = time.time()
result_list = []
for x in python_list:
  result_list.append(x**2) # [1,2,3,4,5,6] ---> [1, 4, 9, 16, 25, 36]
list_duration = time.time() - start_time
print(f"Python List time:  {list_duration:.5f} seconds")

# 2. Time the NumPy Array operation
start_time = time.time()
array_result = numpy_array ** 2
array_duration = time.time() - start_time
print(f"NumPy Array time:  {array_duration:.5f} seconds")

# Calculate the speedup factor
try:
    speedup = list_duration / array_duration
    print(f"\n NumPy is roughly {speedup:.1f}x faster than standard Python lists!")
except ZeroDivisionError:
    print("Error: NumPy operation took 0 time.")

Python List time:  1.01549 seconds
NumPy Array time:  0.00443 seconds

 NumPy is roughly 229.3x faster than standard Python lists!

NumPy is built to be a high-performance numerical calculator. If your dataset requires mixing text, integers, and lists together across columns, a raw NumPy array is the wrong tool. You should use a Pandas DataFrame instead, which is explicitly designed to handle mixed data types column-by-column while preserving NumPy's underlying speed!

In [3]:
# The Correct Way: Strict, clean numerical data types
nums = np.array([1, 2, 3])
print("Clean Array Type:", nums.dtype)

# The Warning Example: Mixing types causes silent string conversion
mixed = np.array([1, 2.5, "three"])
print("\nMixed Array Elements:", mixed)   # Output items are wrapped in quotes: ['1' '2.5' 'three']
print("Mixed Array Type:", mixed.dtype)   # Converted to a Unicode string type (e.g., <U32)

Clean Array Type: int64

Mixed Array Elements: ['1' '2.5' 'three']
Mixed Array Type: <U32

"Now it's your turn. Let's practice vectorized operations.

I want you to create a 1D NumPy array holding five temperature readings in Celsius: [0, 15, 22.5, 30, 40].

Using standard mathematical operators and your array variable, convert all of them to Fahrenheit in a single line of code.

The formula is: $F = (C \times 1.8) + 32$.

Print the result.

In [ ]:
celsius_temps = np.array([0, 15, 22.5, 30, 40])
fahrenheit_temps = (celsius_temps *(9/5)) + 32
print("Temperatures in Fahrenheit:", fahrenheit_temps)

Temperatures in Fahrenheit: [ 32.   59.   72.5  86.  104. ]

In [4]:
# Creating a 2D array (Grid of student grades)
# Structure: 3 rows (students), 2 columns (Math vs Science scores)
grades = np.array([
    [85, 92],
    [90, 88],
    [70, 75]
])

print("The 2D Array Layout:\n", grades)
print(type(grades))
print("\nChecking the structural layout (.shape):", grades.shape) # Output: (3, 2)

The 2D Array Layout:
 [[85 92]
 [90 88]
 [70 75]]
<class 'numpy.ndarray'>

Checking the structural layout (.shape): (3, 2)

In [ ]:
# Reorganizing a 3x2 matrix into a 2x3 matrix
reshaped_grades = grades.reshape(2, 3)
print("Reshaped Matrix (2x3):\n", reshaped_grades)

print("-" * 50)

# Error Demonstration: Violating total elements balance
try:
    grades.reshape(2, 4) # 3x2 = 6 elements, cannot fit into 8 slots!
except ValueError as e:
    print("❌ Reshape Error Caught:", e)

Reshaped Matrix (2x3):
 [[85 92 90]
 [88 70 75]]
--------------------------------------------------
❌ Reshape Error Caught: cannot reshape array of size 6 into shape (2,4)

**Demystifying Dimensional Notation: (10,) vs (10, 1)**

- "When debugging data science pipelines, you will frequently see two confusing shape printouts: (10,) and (10, 1). Even though both structures hold exactly 10 data numbers, NumPy treats them with an entirely different mathematical architecture.

- (10,) indicates a 1D Array. It is a flat sequence of numbers. It has no rows, no columns, and only exists along one directional vector axis. The lone comma is simply Python syntax confirming this is a single-dimension tuple.

- (10, 1) indicates a 2D Array Matrix. It explicitly tells your system: 'I have exactly 10 rows and 1 column.'

- If you try to pass a flat (10,) array to a machine learning library like Scikit-Learn that explicitly requires features organized as columns, your model will crash. You must explicitly reshape it to give it 2D column properties."

In [ ]:
# Defining a flat 1D vector vs a 2D column vector
vector_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(vector_1d)
print(type(vector_1d))
vector_1d.shape

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>

(10,)

In [ ]:
column_2d = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

print("Flat Vector Shape: ", vector_1d.shape) # Output: (10,)
print("Column Matrix Shape:", column_2d.shape) # Output: (10, 1)

print("\nVisualizing Flat Vector Layout:")
print(vector_1d)

print("\nVisualizing Column Matrix Layout:")
print(column_2d)

Flat Vector Shape:  (10,)
Column Matrix Shape: (10, 1)

Visualizing Flat Vector Layout:
[ 1  2  3  4  5  6  7  8  9 10]

Visualizing Column Matrix Layout:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]

In [ ]:
nums = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

nums.shape

(3, 2)

In [ ]:
nums.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
nums.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
nums.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
nums.reshape(6, )

array([1, 2, 3, 4, 5, 6])

**The Data Science Pro-Tip: .reshape(-1, 1)**

- "In real-world production data engineering, you rarely know exactly how many rows of data you have in advance. If your script reads a live user dataset, it might find 100 rows today and 1,000 rows tomorrow. If you hardcode your reshape parameter numbers, your code will inevitably break when the dataset sizes shift.

- To make your code completely dynamic, we use -1 inside our reshape arguments. The -1 tells NumPy: 'Calculate the total item count, divide it by the remaining dimensions provided, and fill in the blank row count automatically for me.'

- Therefore, .reshape(-1, 1) dynamically forces an array of any size into a single vertical column with 1 explicit column, instantly bulletproofing your workflow."

In [2]:
# Reshaping datasets dynamically without hardcoded bounds
small_stream = np.array([10, 20, 30, 40])       # 4 elements
large_stream = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # 8 elements

# Automating column conversion using -1
col_small = small_stream.reshape(-1, 1)
col_large = large_stream.reshape(-1, 1)

print("Small Stream Dynamic Shape:", col_small.shape) # Evaluated automatically to (4, 1)
print("Large Stream Dynamic Shape:", col_large.shape) # Evaluated automatically to (8, 1)

Small Stream Dynamic Shape: (4, 1)
Large Stream Dynamic Shape: (8, 1)

In [ ]:
x = np.array([1,2,3,4,5,6])

print(x.shape)
print(x)
print(x.reshape(1,6))
print(x.reshape(6,1))

(6,)
[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

In [ ]:
x = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
x.shape

(2, 2, 2)

In [ ]:
x.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
x.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
test_scores = np.array([45, 82, 91, 58, 73, 66, 95, 38])

# Step 1: Create the boolean mask condition
passing_mask = test_scores >= 60
print("The Filter Mask:", passing_mask) # Output array of True/False flags

# Step 2: Extract data meeting the condition by passing the mask back into the array bracket
passing_scores = test_scores[passing_mask]
print("Filtered Passing Scores:", passing_scores)

The Filter Mask: [False  True  True False  True  True  True False]
Filtered Passing Scores: [82 91 73 66 95]

In [ ]:
# Rows: Students, Columns: [Math, Science, English]
grade_matrix = np.array([
    [80, 90, 85], # Student 1
    [95, 85, 92], # Student 2
    [60, 70, 65]  # Student 3
])

# Column averages (Average performance score achieved per subject class)
subject_means = np.mean(grade_matrix, axis=0)
print("Subject Performance Averages (Math, Sci, Eng):", subject_means)

# Row averages (Overall average grade earned per individual student)
student_means = np.mean(grade_matrix, axis=1)
print("Individual Student Grade Averages:", student_means)

Subject Performance Averages (Math, Sci, Eng): [78.33333333 81.66666667 80.66666667]
Individual Student Grade Averages: [85.         90.66666667 65.        ]

In [ ]:
grade_matrix.reshape(-1,1).shape

(9, 1)

In [ ]:
x = np.array([[1,2,3,5], [12,13,4,5]])
x.shape

(2, 4)

In [ ]:
x.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 5],
       [12],
       [13],
       [ 4],
       [ 5]])

In [ ]:
x.reshape(1,-1)

array([[ 1,  2,  3,  5, 12, 13,  4,  5]])

In [ ]:
x.reshape(-1,2)

array([[ 1,  2],
       [ 3,  5],
       [12, 13],
       [ 4,  5]])

In [ ]:
grade_matrix.reshape(1, -1)

array([[80, 90, 85, 95, 85, 92, 60, 70, 65]])

### **Pandas**

- NumPy is a mathematical powerhouse. It handles millions of numbers instantly because it packs them tightly into clean grids. But out in the industry, real-world data isn't just a grid of pure numbers. Think of an online store's database or a hospital's records—you have text names, dates, true/false payment flags, and decimal costs mixed together.

- If we throw all of that into NumPy, its strict data homogeneity rule forces everything into a text string, breaking our ability to do math. Furthermore, NumPy grids don't have column headers. You have to remember that Column 0 is 'Age' and Column 1 is 'Salary'.

- To solve this, we upgrade to Pandas. Pandas is built directly on top of NumPy, keeping its underlying blazing speed, but it wraps our data in labels. It gives us row indices and column names, turning raw data into an interactive, supercharged Excel spreadsheet right inside Python.

In [ ]:
import pandas as pd
import numpy as np

# Real-World Scenario: Tracking peak summer temperatures in Indian Metros
# Passing a native Python list or NumPy array, and providing matching index labels
city_temps = pd.Series(
    [28, 32, 25, 38],
    index=["Bangalore", "Chennai", "Mumbai", "Delhi"]
)

print("--- The Labeled Series ---")
print(city_temps)

print("\n--- Accessing Data by Label ---")
# Instead of city_temps[1], we use an explicit descriptive key
print(f"The temperature in Chennai is: {city_temps['Chennai']}°C")

print("\n--- Vectorized Operations still work! ---")
# Just like NumPy, we can perform math across the whole Series instantly without loops
print(city_temps + 2)

--- The Labeled Series ---
Bangalore    28
Chennai      32
Mumbai       25
Delhi        38
dtype: int64

--- Accessing Data by Label ---
The temperature in Chennai is: 32°C

--- Vectorized Operations still work! ---
Bangalore    30
Chennai      34
Mumbai       27
Delhi        40
dtype: int64

**Pandas DataFrame — The Full Spreadsheet Table**

- "If a Series is a single column of data, what happens when you stack multiple columns side-by-side, sharing the exact same row index? You get a DataFrame.

- A DataFrame is your complete, structural tabular spreadsheet in Python. It is a two-dimensional object where every column can have a completely different data type. Column 1 can contain text strings, Column 2 can contain decimal floats, and Column 3 can contain booleans. This breaks the homogeneity limitations of NumPy while preserving operational speed.

- The easiest way to construct a DataFrame from scratch is using a Python Dictionary. The dictionary keys automatically transform into your Column Headers, and the lists assigned to those keys provide your Column Values.

In [ ]:
import pandas as pd

# Real-World Scenario: Technical Recruitment / HR Screening Dataset
hr_data = {
    "Candidate_Name": ["Ananya", "Rohan", "Priya", "Amit"],
    "Years_Experience": [2, 5, 3, 8],
    "Technical_Score":  [88.5, 91.0, 79.5, 95.0],
    "Passed_Screening": [True, True, False, True] # Mixing types: Strings, Ints, Floats, Booleans!
}

# Convert dictionary to DataFrame
df = pd.DataFrame(hr_data)

print("--- The HR Candidate DataFrame ---")
print(df)

print("\n--- Getting Structural Metadata ---")
print("Table Shape (Rows, Columns):", df.shape) # Inherited directly from NumPy!
print("Column Names in Table:      ", df.columns.tolist())

--- The HR Candidate DataFrame ---
  Candidate_Name  Years_Experience  Technical_Score  Passed_Screening
0         Ananya                 2             88.5              True
1          Rohan                 5             91.0              True
2          Priya                 3             79.5             False
3           Amit                 8             95.0              True

--- Getting Structural Metadata ---
Table Shape (Rows, Columns): (4, 4)
Column Names in Table:       ['Candidate_Name', 'Years_Experience', 'Technical_Score', 'Passed_Screening']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Candidate_Name    4 non-null      object
 1   Years_Experience  4 non-null      int64
 2   Technical_Score   4 non-null      float64
 3   Passed_Screening  4 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 232.0+ bytes

**Understanding the Relationship: Series vs DataFrame**

- "It is critical to realize that a DataFrame is not a completely independent tool; it is structurally built out of individual Series glued together.

- If you pull out a single solitary column from a multi-column DataFrame, Pandas will extract it and hand it to you as a Series object. If you view the entire structural table, it is a DataFrame. You will constantly navigate between these two object types throughout your day as a data scientist."

In [ ]:
# Isolating a single column from our DataFrame
scores_column = df["Technical_Score"]

print("--- Extracted Column Vector ---")
print(scores_column)

print("\n--- Data Type Verification ---")
print("Type of a single column extraction:", type(scores_column)) # Output: pandas.core.series.Series
print("Type of the full database table:   ", type(df))            # Output: pandas.core.frame.DataFrame

--- Extracted Column Vector ---
0    88.5
1    91.0
2    79.5
3    95.0
Name: Technical_Score, dtype: float64

--- Data Type Verification ---
Type of a single column extraction: <class 'pandas.core.series.Series'>
Type of the full database table:    <class 'pandas.core.frame.DataFrame'>

Until now, we have been hardcoding small dictionaries and lists into our code. But in the real world, data lives in external files. The most universal file format in data science is the CSV, or Comma-Separated Values file.

If you open a CSV in a basic text editor, it's just raw rows of text where each value is separated by a literal comma. Pandas allows us to ingest this text file in a single line of code using pd.read_csv(). It automatically parses the commas, structures the alignment, builds row indices, and hands you a beautifully formatted DataFrame.

Today, we are loading the legendary Titanic Dataset directly from a live web URL. This dataset contains real historical records of the passengers aboard the Titanic. The moment we load it, our absolute first line of defense is to check its .shape to see exactly how massive our data matrix is.

In [ ]:
import pandas as pd

# 1. Define the live URL to the dataset repository
url = "https://raw.githubusercontent.com/dsrscientist/dataset1/master/titanic_train.csv"

# Production Guardrail: Network connectivity fail-safe for Google Colab
df = pd.read_csv(url)
print("✅ Live dataset successfully loaded from GitHub URL!")

# 2. Inspect the matrix layout dimensions
print(f"Dataset Shape (Rows, Columns): {df.shape}") # Output: (891, 12)

✅ Live dataset successfully loaded from GitHub URL!
Dataset Shape (Rows, Columns): (891, 12)

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

- "One of the most dangerous beginner mistakes you can make in data science is typing print(df) on a massive dataset. If your file has 5 million rows, trying to print the whole thing will lag your browser, flood your notebook, and can crash your Google Colab instance.

- Instead, data scientists 'peek' at the data using .head() and .tail().

- .head() acts as a preview, showing you the very first 5 rows of your table by default.

- .tail() lets you examine the end of the file, which is incredibly useful for verifying that your data wasn't cut off or corrupted during transmission.

- If you want to see a specific number of rows, just pass an integer directly inside the parentheses."

In [ ]:
print("--- Peeking at the top 5 rows (.head()) ---")
# Essential preview step to inspect column alignment
print(df.head())

print("\n" + "="*80 + "\n")

print("--- Peeking at the bottom 3 rows (.tail(3)) ---")
# Explicitly asking for exactly 3 records instead of the default 5
print(df.tail(3))

--- Peeking at the top 5 rows (.head()) ---
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

================================================================================

--- Peeking at the bottom 3 rows (.tail(3)) ---
     PassengerId  Survived  Pclass                                      Name  \
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q

In [ ]:
df.tail(25)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
870,871,0,3,"Balkic, Mr. Cerin",male,26.0,0,0,349248,7.8958,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

"Now that we know what the data looks like visually, we need to perform a structural audit. We do this using the .info() function.

Think of .info() as a comprehensive medical check-up for your dataset. It tells you three critical pieces of information:

The exact name of every column.

The memory data types (Dtype) of each column—helping you ensure numbers are tracked as integers or floats, and text is classified as objects.

The Non-Null Count. This is your primary metric for finding missing data.

If our shape told us we have 891 total rows, then every column should ideally show '891 non-null'. If a column like Age shows only '714 non-null', that means there are missing values. Someone forgot or was unable to record the age for those specific individuals. Finding these gaps is the very first step of data preprocessing before training any machine learning models."

In [ ]:
print("--- Executing Structural Audit ---")
df.info()

--- Executing Structural Audit ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

"To pull out a specific column from a spreadsheet, we pass its text name inside square brackets directly after our DataFrame variable name.

However, there is a fundamental syntax rule that trips up almost everyone:

Single Brackets df['Column']: This extracts one single column and hands it back to you as a 1D Pandas Series.

Double Brackets df[['Col1', 'Col2']]: This extracts a subset of multiple columns and hands it back as a structured, 2D DataFrame.

Think of the inner set of brackets as a Python list. You are creating a list of text strings representing the columns you want, and passing that list into the outer selection brackets. If you try to pass multiple column names into single brackets, Python will throw a KeyError because it thinks you are looking for one giant column with a comma in its name."

In [ ]:
# 1. Single Bracket Selection -> Returns a 1D Series
passenger_ages = df["Age"]
print("--- Single Bracket Selection Type ---")
print(type(passenger_ages)) # <class 'pandas.core.series.Series'>
print(passenger_ages.head(3))

print("\n" + "="*50 + "\n")

# 2. Double Bracket Selection -> Returns a 2D DataFrame
demographics = df[["Name", "Age", "Survived"]]
print("--- Double Bracket Selection Type ---")
print(type(demographics)) # <class 'pandas.core.frame.DataFrame'>
print(demographics.head(3))

print("\n" + "="*50 + "\n")

--- Single Bracket Selection Type ---
<class 'pandas.core.series.Series'>
0    22.0
1    38.0
2    26.0
Name: Age, dtype: float64

==================================================

--- Double Bracket Selection Type ---
<class 'pandas.core.frame.DataFrame'>
                                                Name   Age  Survived
0                            Braund, Mr. Owen Harris  22.0         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                             Heikkinen, Miss. Laina  26.0         1

==================================================

In [ ]:
df["Name", "Age"] # This will crash!

KeyError: ('Name', 'Age')